version: '3.7'
services:
  ########################
  # SETUP DB CONTAINER
  ########################
  mongodb:
    container_name: container_mongodb
    image: mongo:latest
    env_file: .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - storage_v1:/data/db
    networks:
      - network
  # #######################
  # SETUP API CONTAINER
  # #######################
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: container_api
    env_file: .env
    volumes:
      - ./api:/usr/src/app
    ports:
      - ${API_PORT}:${API_PORT}
    links:
      - mongodb
    networks:
      - network
    command: yarn dev
    # restart: always
  # #######################
  # SETUP WEB CONTAINER
  # #######################
  web:
    container_name: container_web
    build:
      context: ./web
      dockerfile: Dockerfile
    # links:
    #   - api
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    networks:
      - network

networks:
    network:
        driver: bridge

volumes:
    storage_v1:
 
