# Dockerfile for client

# Stage 1: Build react client
FROM node:10.16-alpine

# Working directory be app
RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package*.json ./

# Install dependencies
RUN yarn install

# copy local files to app folder
COPY . .

EXPOSE 3000

CMD ["./node_modules/.bin/react-scripts", "start"]
